### PR TITLE
fix for PHP 7.3

### PR DESCRIPTION
**Pull request by remicollet**
From UPGRAGIN.INTERNALS

` r.  fields of php_url struct change from char * to zend_string *`

### CODE REVIEW

**Comment by pmjones** [comment]
@remicollet Thanks!

@jbboehr Look good to you?

**Comment by remicollet** [comment]
Second commit useful in all version, but PHP < 7.3 strangely don't raise these warnings

Example:
```
/dev/shm/BUILD/php73-php-pecl-request-1.0.0/NTS/serverresponse.c:588:54: warning: field precision specifier '.*' expects argument of type 'int', but argument 4 has type 'size_t {aka long unsigned int}' [-Wformat=]
                             "JSON encoding failed: %.*s", Z_STRLEN(json_errmsg), Z_STRVAL(json_errmsg));

```

**Comment by remicollet** [comment]
OK, travis is happy with older version, and local build:

```
=====================================================================
PHP         : /opt/remi/php73/root/usr/bin/php 
PHP_SAPI    : cli
PHP_VERSION : 7.3.0alpha2
ZEND_VERSION: 3.3.0-dev
PHP_OS      : Linux - Linux builder.remirepo.net 4.16.16-200.fc27.x86_64 #1 SMP Sun Jun 17 03:06:00 UTC 2018 x86_64
INI actual  : /dev/shm/BUILD/php73-php-pecl-request-1.0.0/NTS
More .INIs  :   
CWD         : /dev/shm/BUILD/php73-php-pecl-request-1.0.0/NTS
Extra dirs  : 
VALGRIND    : Not used
=====================================================================
Running selected tests.
PASS request phpinfo [tests/phpinfo.phpt] 
....
PASS ServerResponse::setVersion [tests/response/setVersion.phpt] 
=====================================================================
Number of tests :   72                71
Tests skipped   :    1 (  1.4%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   71 ( 98.6%) (100.0%)
---------------------------------------------------------------------
Time taken      :    2 seconds
=====================================================================

```

**Comment by jbboehr** [comment]
@pmjones Yep, LGTM.

**Comment by pmjones** [comment]
@jbboehr Merged! Appveyor was unhappy, though -- is that a problem?

**Comment by pmjones** [comment]
@remicollet Thanks for this!

**Comment by jbboehr** [comment]
@pmjones Looks like the download URLs for the windows build artifacts changed again. Should be fixed by #13

**Pull request merged**
